
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Mar 27 19:38:14 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addLaboratory", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addLaboratory", namespace = "http://Laboratory.KyojinService.com/")

public class AddLaboratory {

    @XmlElement(name = "arg0")
    private com.ks.laboratory.model.Laboratory arg0;

    public com.ks.laboratory.model.Laboratory getArg0() {
        return this.arg0;
    }

    public void setArg0(com.ks.laboratory.model.Laboratory newArg0)  {
        this.arg0 = newArg0;
    }

}

