
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Mar 27 19:38:14 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "deleteResearcher", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteResearcher", namespace = "http://Laboratory.KyojinService.com/")

public class DeleteResearcher {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

