
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Mar 27 19:38:14 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "deleteLaboratoryResponse", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteLaboratoryResponse", namespace = "http://Laboratory.KyojinService.com/")

public class DeleteLaboratoryResponse {

    @XmlElement(name = "return")
    private java.lang.Boolean _return;

    public java.lang.Boolean getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.Boolean new_return)  {
        this._return = new_return;
    }

}

