
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 09 08:49:59 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getResearcherResponse", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getResearcherResponse", namespace = "http://Laboratory.KyojinService.com/")

public class GetResearcherResponse {

    @XmlElement(name = "return")
    private com.ks.laboratory.model.Researcher _return;

    public com.ks.laboratory.model.Researcher getReturn() {
        return this._return;
    }

    public void setReturn(com.ks.laboratory.model.Researcher new_return)  {
        this._return = new_return;
    }

}

