
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Mar 27 19:38:14 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "linkResearcherToLaboratory", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linkResearcherToLaboratory", namespace = "http://Laboratory.KyojinService.com/", propOrder = {"researcherId", "laboratoryId"})

public class LinkResearcherToLaboratory {

    @XmlElement(name = "researcherId")
    private int researcherId;
    @XmlElement(name = "laboratoryId")
    private int laboratoryId;

    public int getResearcherId() {
        return this.researcherId;
    }

    public void setResearcherId(int newResearcherId)  {
        this.researcherId = newResearcherId;
    }

    public int getLaboratoryId() {
        return this.laboratoryId;
    }

    public void setLaboratoryId(int newLaboratoryId)  {
        this.laboratoryId = newLaboratoryId;
    }

}

