
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Mar 27 11:44:01 CET 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "newResearcher", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newResearcher", namespace = "http://Laboratory.KyojinService.com/", propOrder = {"Id", "FirstName", "LastName", "resAge"})

public class NewResearcher {

    @XmlElement(name = "Id")
    private int Id;
    @XmlElement(name = "FirstName")
    private java.lang.String FirstName;
    @XmlElement(name = "LastName")
    private java.lang.String LastName;
    @XmlElement(name = "resAge")
    private int resAge;

    public int getArg0() {
        return this.Id;
    }

    public void setArg0(int newArg0)  {
        this.Id = newArg0;
    }

    public java.lang.String getArg1() {
        return this.FirstName;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.FirstName = newArg1;
    }

    public java.lang.String getArg2() {
        return this.LastName;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.LastName = newArg2;
    }

    public int getArg3() {
        return this.resAge;
    }

    public void setArg3(int newArg3)  {
        this.resAge = newArg3;
    }

}

