
package com.ks.laboratory.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 09 08:49:59 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "ResearchersLaboratory", namespace = "http://Laboratory.KyojinService.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResearchersLaboratory", namespace = "http://Laboratory.KyojinService.com/")

public class ResearchersLaboratory {

    @XmlElement(name = "researcherId")
    private int researcherId;

    public int getResearcherId() {
        return this.researcherId;
    }

    public void setResearcherId(int newResearcherId)  {
        this.researcherId = newResearcherId;
    }

}

