
package edu.webservice.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResearcherManagementImpl", targetNamespace = "http://service.webservice.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResearcherManagementImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:AddLaboratory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLaboratory", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.AddLaboratory")
    @ResponseWrapper(localName = "addLaboratoryResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.AddLaboratoryResponse")
    public int addLaboratory(
        @WebParam(name = "arg0", targetNamespace = "")
        Laboratory arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:LinkLaboratoryResearcher")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "linkLaboratoryResearcher", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.LinkLaboratoryResearcher")
    @ResponseWrapper(localName = "linkLaboratoryResearcherResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.LinkLaboratoryResearcherResponse")
    public int linkLaboratoryResearcher(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.webservice.service.Laboratory
     */
    @WebMethod(action = "urn:GetLaboratory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLaboratory", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetLaboratory")
    @ResponseWrapper(localName = "getLaboratoryResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetLaboratoryResponse")
    public Laboratory getLaboratory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.webservice.service.Laboratory>
     */
    @WebMethod(action = "urn:GetAllLaboratorys")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLaboratorys", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetAllLaboratorys")
    @ResponseWrapper(localName = "getAllLaboratorysResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetAllLaboratorysResponse")
    public List<Laboratory> getAllLaboratorys();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:AddResearcher")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addResearcher", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.AddResearcher")
    @ResponseWrapper(localName = "addResearcherResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.AddResearcherResponse")
    public int addResearcher(
        @WebParam(name = "arg0", targetNamespace = "")
        Researcher arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "urn:DeleteResearcher")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteResearcher", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.DeleteResearcher")
    @ResponseWrapper(localName = "deleteResearcherResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.DeleteResearcherResponse")
    public Boolean deleteResearcher(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "urn:GetAllLaboratoryResearcher")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLaboratoryResearcher", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetAllLaboratoryResearcher")
    @ResponseWrapper(localName = "getAllLaboratoryResearcherResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetAllLaboratoryResearcherResponse")
    public List<String> getAllLaboratoryResearcher();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "urn:DeleteLaboratory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLaboratory", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.DeleteLaboratory")
    @ResponseWrapper(localName = "deleteLaboratoryResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.DeleteLaboratoryResponse")
    public Boolean deleteLaboratory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.webservice.service.Researcher>
     */
    @WebMethod(action = "urn:GetAllResearchers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllResearchers", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetAllResearchers")
    @ResponseWrapper(localName = "getAllResearchersResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetAllResearchersResponse")
    public List<Researcher> getAllResearchers();

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.webservice.service.Researcher
     */
    @WebMethod(action = "urn:GetResearcher")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResearcher", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetResearcher")
    @ResponseWrapper(localName = "getResearcherResponse", targetNamespace = "http://service.webservice.edu/", className = "edu.webservice.service.GetResearcherResponse")
    public Researcher getResearcher(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
