
package edu.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 15 11:16:21 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllLaboratorys", namespace = "http://service.webservice.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllLaboratorys", namespace = "http://service.webservice.edu/")

public class GetAllLaboratorys {


}

