
package edu.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 15 11:46:10 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllLaboratoryResearcherResponse", namespace = "http://service.webservice.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllLaboratoryResearcherResponse", namespace = "http://service.webservice.edu/")

public class GetAllLaboratoryResearcherResponse {

    @XmlElement(name = "return")
    private java.util.Collection<java.lang.String> _return;

    public java.util.Collection<java.lang.String> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.Collection<java.lang.String> new_return)  {
        this._return = new_return;
    }

}

