
package edu.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 15 11:46:10 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllLaboratoryResearcher", namespace = "http://service.webservice.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllLaboratoryResearcher", namespace = "http://service.webservice.edu/")

public class GetAllLaboratoryResearcher {


}

